repos:
-   repo: https://github.com/nsonaniya2010/detect-secrets-test
    rev: v0.3
    hooks:
    -   id: detect-secrets
        args: ['-n', '--baseline', 'baseline', '--exclude-files', '^go.sum$|^Gopkg.lock$|^package-lock.json']
